/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.cacheblasters.realms.npc.definition";

export { $nsid };

/** An NPC definition template. Servers define NPC behavior via the behavior field and dialogue trees. */
type Main = {
  $type: "com.cacheblasters.realms.npc.definition";
  name: string;
  description: string;

  /**
   * NPC behavior archetype
   */
  behavior: "hostile" | "merchant" | "questgiver" | "wanderer" | "static" | l.UnknownString;
  level?: number;

  /**
   * Optional pacing hint for pulse-combat systems: game ticks between this NPC's attacks (1 = every tick). Systems with a different combat pacing model may ignore it.
   */
  attackCooldown?: number;

  /**
   * Open map of attribute ID -> value, using server's attribute schema
   */
  attributes?: l.LexMap;

  /**
   * Dialogue tree structure — server-defined format
   */
  dialogue?: l.LexMap;

  /**
   * ASCII art lines displayed during combat
   */
  art?: string[];

  /**
   * Item definition IDs this merchant sells (merchant NPCs only)
   */
  shop?: string[];
  tags?: string[];
};

export type { Main };

/** An NPC definition template. Servers define NPC behavior via the behavior field and dialogue trees. */
const main = l.record<"any", Main>(
  "any",
  $nsid,
  l.object({
    name: l.string({ maxLength: 128 }),
    description: l.string({ maxLength: 4096 }),
    behavior: l.string<{
      knownValues: ["hostile", "merchant", "questgiver", "wanderer", "static"];
    }>(),
    level: l.optional(l.integer({ minimum: 1 })),
    attackCooldown: l.optional(l.withDefault(l.integer({ minimum: 1 }), 1)),
    attributes: l.optional(l.lexMap()),
    dialogue: l.optional(l.lexMap()),
    art: l.optional(l.array(l.string())),
    shop: l.optional(l.array(l.string())),
    tags: l.optional(l.array(l.string())),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
